files:
  - source: '*'
    ignore:
      - '*.py'
      - '*.bat'
      - Makefile
      - '*.sh'
      - .gitignore
      - /images
      - /*/source/images
      - Vagrantfile
      - /logos
    translation: '%original_path%/%original_file_name%'
